### ISSUE TITLE
[Bug] Emojis doesn't show in dialog list

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#100]
Console output:
<pre>
qrc:/qml/Cutegram/AccountDialogList.qml:244:17: QML Text: Invalid image data: qrc:/qml/Cutegram/AccountDialogList.qml
</pre>
![screenshot](https://cloud.githubusercontent.com/assets/8397079/8402384/dc570fc2-1e54-11e5-88d5-63cdec4c9d76.png)

**Comment by realbardia** [comment]
Fixed... Thank you for reporting.
