### ISSUE TITLE
Position of windows not memorized

### ISSUE THREAD

**Issue by Simulacrux** [Aseman-Land/Cutegram#101]
Hello, 

I discovered a little glitch on my Windows (7/8.1/10) maschines. Everytime I minimize the Cutegram program to the Tray-Icon and reopen it from there, the Cutegram window opens up in the middle of my first monitor. It would be great, if the position and the correct monitor (e.g. second) of the program would be memorized before minimization and restored correctly after maximize it again. 
A similar glitch is on the "Open in new window" command for chating in a seperate window. This command everytime opens up a new window in the middle of the main program and with a predefined size. It would be nice, if this could also memorize the last used size and position. If not for every contact seperately but at least the last used position/size for every contact.

Cheers Simulacrux

**Comment by realbardia** [comment]
Hi... thank you for suggestion.
Added :)
