### ISSUE TITLE
[Bug] Message text in dialog list doesn't elided

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#102]
Quick research shows:
* maximumLineCount: 1 <-- This property is not supported for rich text (http://doc.qt.io/qt-5/qml-qtquick-text.html#maximumLineCount-prop)
* eliding with rich text (https://bugreports.qt.io/browse/QTBUG-16567 and https://stackoverflow.com/questions/29921385/qml-use-texts-elide-property-with-textformat-richtext)

Also, I have noticed that emoji is not anti-aliased.

![lines](https://cloud.githubusercontent.com/assets/8397079/8404922/50176852-1e6a-11e5-9348-6cdbbb6f788e.png)

**Comment by realbardia** [comment]
We are using Text component on the DialogList. They using TextEdit component on the links.
So I use another trick to fix these bug. It's not fixed because this is the Qt problem. But I changed lineHeight to fix this problem.
Anti-aliased problem fixed too.
Thank you
