### ISSUE TITLE
Build procedure on Windows

### ISSUE THREAD

**Issue by ezdev128** [Aseman-Land/Cutegram#108]
Hello,
Is there any documented build procedure under VS2010 (at least)? 
Thanks!

**Comment by Sollex-21412** [comment]
1. Visual Studio 2010
2. Qt 5.4.0
3. Qt Visual Stuido add-in

Just import Cutegram's project file to VS via Qt add-in. Resolve dependency (zlib, openssl) and enjoy ;)
