### ISSUE TITLE
[Feature Request] Add possibility to select emoji themes

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#117]
Please add possibility to select emoji themes via Configure.

**Comment by legion1978** [comment]
I still dont see whats the problem with the "official" telegram emojis. the ones on cutegram dont look crisp (sometimes i even have trouble making them from one to another). some insight here? thnx!

**Comment by auchri** [comment]
+1

**Comment by realbardia** [comment]
It's because Twemoji is released under the MIT license and Is open source.
We'll add emoji theme switcher in the next release.

**Comment by Sollex-21412** [comment]
blocked by  #121.

**Comment by auchri** [comment]
why blocked?

**Comment by Sollex-21412** [comment]
@auchri, not blocked but refs )
