### ISSUE TITLE
[Feature request] Paste clipboard image

### ISSUE THREAD

**Issue by intrd** [Aseman-Land/Cutegram#12]
One of the most useful feature in TDesktop that we really apreciate in Cutegram..

**Comment by realbardia** [comment]
Thank you for suggestion.
We'll add it in the next release :)

**Comment by intrd** [comment]
Thanks! meanwhile... solved w/ a trick using ShareX..

**Comment by Thunderpig72** [comment]
The next release came out quite recently, but it seems this isn't added. At least not to the Windows version. Am I missing something?

**Comment by realbardia** [comment]
Hi... I was forget It. Sorry.
I'll add it soon.

**Comment by realbardia** [comment]
Added. Thank you for suggestion and Sorry again for delay :)
