### ISSUE TITLE
Use Emoji One instead of Twitter's emojis?

### ISSUE THREAD

**Issue by Dyras** [Aseman-Land/Cutegram#123]
Hello. May I suggest switching from Twitter's emojis to Emoji One? EO, just like Twitter's emojis, is open source. They are also verry pretty, and they are of a higher resolution than Twitter's emojis. They also look more like Apple's emojis, so they will match Telegram better.

Perhaps you could add Emoji One as the standard set, and use Twitter as an optional set?

http://emojione.com/

Here's how to install it, along with how you can use Emoji One:
http://emojione.com/developers

**Comment by Sollex-21412** [comment]
Will be possible after #117 and #121 will be implemented.

**Comment by Dyras** [comment]
Yup. Figured that much, but my suggestion was to use Emoji One as the new standard because I think that would be more attractive to people trying out the program.

**Comment by KAMiKAZOW** [comment]
@Dyras: You can close this bug. See https://github.com/Aseman-Land/Cutegram/commit/1dbe2792fb5a1760339379907f906e236c09db84

**Comment by Dyras** [comment]
Perfect!
