### ISSUE TITLE
[FRQ] Please add a way to disable the transparency when you click a name in a conversation

### ISSUE THREAD

**Issue by Dyras** [Aseman-Land/Cutegram#125]
Hi. I think there should be an option to disable the transparency effect that happens when you click on someones name, or perhaps change the way you enable the transparency. I suggest you change so that you have to right click the persons name and click "Only show his/her messages" instead of the current behavior, because I've chatted with 2 other people with Cutegram and they were both confused over how they triggered this. To be honest, so was I the first time.

This is what I'm talking about:
![image](https://cloud.githubusercontent.com/assets/12563436/8579079/b852d376-25b2-11e5-80b5-cf972092aed9.png)

**Comment by realbardia** [comment]
Transparency feature disabled by default under the new release :)
