### ISSUE TITLE
Can't send image from webcam

### ISSUE THREAD

**Issue by PolynomialDivision** [Aseman-Land/Cutegram#126]
Hi,
when I'm selecting the webcam in the chat fenster this error message is shown by starting cutegram --verbose

``` bash
error "MAX_DATE_INVALID" "messagesReadEncryptedHistory"
tg.core.session: error for query "559e4ca400000000"  : 400  : "MAX_DATE_INVALID"
error "MAX_DATE_INVALID" "messagesReadEncryptedHistory"
```

I'm able to take a picture but after clicking send nothing happens.
There isn't even a console output.

**Comment by Polynomdivison** [comment]
Version:
Cutegram 2.5.0

OS:
Xubuntu 15.04
3.19.0-22-generic

**Comment by realbardia** [comment]
Hi... Thank you for reporting.
We'll fix it soon :)
