### ISSUE TITLE
Private chats are store in the filesystem (sqlite3) in plaintext

### ISSUE THREAD

**Issue by borjiviri** [Aseman-Land/Cutegram#127]
# secret chats stored in plaintext
I think that storing the secret chats in plaintext is just missing the point what is Telegram about. Please do not store secret chats on the filesystem, or if stored, use the encryption keys of the conversations. Also it would be a good idea to have an config option to allow (or deny) to store the public & secret chats

Evidence:
1.- Open a secret chat with a friend and write something
2. Grep your conversation in ~/.config/Cutegram/your_phone_numer/database.db
```sh
$ echo 'select message from Messages;' \
    | sqlite3 ~/.config/Cutegram/XXXXXXX/database.db \
    | grep  "probando probando"
probando probando
```

**Comment by realbardia** [comment]
Yes. I agree with you. I'm looking for a absolute solution for both of chats (secret chat and normal chat). In fact I believe both of them must store encrypted.
So probably It's our main focus in the next release.
Thank you for reporting :)

**Comment by KAMiKAZOW** [comment]
Um, why?
File system-level encryption is the responsibility of the operating system. Windows has BitLocker, Linux has LUKS, OSX has FileVault, and all of them have TrueCrypt (or whatever fork of it currently en vogue).

**Comment by Sollex-21412** [comment]
@KAMiKAZOW, unfortunately not everybody using system-level encryption. I think, it would be better to use db encryption or value encryption.

**Comment by KAMiKAZOW** [comment]
“unfortunately not everybody use system-level encryption”
– So? If they don't value privacy enough to use encryption, chatlog encryption is not needed anyway. It's only added maintenance for zero benefit.

**Comment by realbardia** [comment]
> Um, why?
File system-level encryption is the responsibility of the operating system. Windows has BitLocker, Linux has LUKS, OSX has FileVault, and all of them have TrueCrypt (or whatever fork of it is currently en vogue).

Ok... I also agree this. In fact I believe both of them is true. But I don't want make a decision about this thread under my personal opinions.
So we have two choice now.

1. We encrypt database in the next release to provide more security on the unencrypted file systems.
2. We leave database unencrypted. But I have an idea, We can add many cool features using unencrypted database in the future. like create plugin for desktop search that allow users to search on the telegram database using desktop search.

more security OR more desktop features
What is your opinion?

I choose second one, because many other apps store their data in the plain text. (like firefox)
And if a user is really concern about the security, should use encrypted file system.

**Comment by borjiviri** [comment]
I think that secret messages should never be kept in filesystem (just to protect the user). 
Regarding "if the other programs don't encrypt stuff means and I don't have to encrypt my stuff" , from my point of view, it's a very poor argument.

Now we live in a post-snowden era, we already know how things works, so please, do behave in consequence.

**Comment by ZephrFish** [comment]
"I think that secret messages should never be kept in filesystem (just to protect the user).
Regarding "if the other programs don't encrypt stuff means and I don't have to encrypt my stuff" , from my point of view, it's a very poor argument."
I agree with this, even if things are to be encrypted on a filesystem the argument about using FDE isn't a valid one as if your drive is compromised while it's 'unlocked' the encryption is no use and a result your confidential secret chats are compromised also!

**Comment by legion1978** [comment]
i really thought db encryption was a de-facto standard for messaging apps (for obvious reasons) D:

i believe its what the user expects anyway. if its a "secret chat" why would i think i need to encrypt my hd? meaning: i dont care if anyone sees what i chat about-- but if i feel i need to keep something confidential, then i open a secret chat. i wouldnt instinctively run to encrypt my hd.. i see "secret" and i think "im safe".. no? how does telegram  handle this?  

btw, how does cutegram handles media files? are they persistant? if i delete some picture, video, audio from cutegram, will it be available if i open telegram (web or app)? i ask cause i had some trouble erasing media files from a friends account because of some sort of persistant (telegram) storage. Files could be found in the phone, even past the time telegram says they need to delete inactive accounts. so im curious about how is this managed by cutegram 

thnx

**Comment by KAMiKAZOW** [comment]
“I think that secret messages should never be kept in filesystem”

Great, all messages are gone once the application is closed. m(
Data loss bug reports in 3, 2, 1, …

**Comment by legion1978** [comment]
"
“I think that secret messages should never be kept in filesystem”
Great, all messages are gone once the application is closed. m(
Data loss bug reports in 3, 2, 1, …"

hehe-- i think it meant something about the server storage thing (which i also mentioned in my precious post) .. maybe retrieving them on program start from telegram server? i dont know really, thats why i asked too :)

**Comment by borjiviri** [comment]
Yeah, I would prefer that secret messages are stored just in memory and encrypted. I think that we all know what "secret" means, right?

**Comment by KAMiKAZOW** [comment]
Secret chats are NOT stored on the server which is why they must be stored on the file system.
No messaging application I know uses encrypted chatlogs.

**Comment by Sollex-21412** [comment]
@KAMiKAZOW, +1
https://telegram.org/privacy

"Secret Chats

Secret chats use end-to-end encryption. This means that all data is encrypted with a key that only you and the recipient know. There is no way for us or anybody else without direct access to your device to learn what content is being sent in those messages. **We do not store your secret chats on our servers.** We also do not keep any logs for messages in secret chats, so after a short period of time we no longer know who or when you messaged via secret chats. For the same reasons secret chats are not available in the cloud — you can only access those messages from the device they were sent to or from."

**Comment by KAMiKAZOW** [comment]
I think some participants here should read the Telegram FAQ first. Apparently they use software they don't understand.

**Comment by Sollex-21412** [comment]
https://telegram.org/faq#secret-chats

**Comment by legion1978** [comment]
we dont need to "understand" software. we need to use it :) -- a common dumb user

**Comment by borjiviri** [comment]
What I think here is that some people just don't understand security ...

**Comment by legion1978** [comment]
that may well be :) but again, common users make assumptions on that the software should do based on what? names? menu entries? tooltips? it says "secret" it should be secret (somehow). period.

**Comment by Sollex-21412** [comment]
I see here three opinions:
1. Encrypt db (dev)
2. Encrypt disk (user)
3. Don't encrypt anything

**Comment by legion1978** [comment]
if secret chats db will be indefinetly stored on disk, it should (must) be encrypted. otherwise it defeats the purpose.

**Comment by Sollex-21412** [comment]
I propose encrypt only secret chat messages not the whole db.

**Comment by borjiviri** [comment]
I propose to encrypt the message db for regular & secret chats. For the secret chats, the configued TTL (msg time to live) of a chat must be enforced, meaning that if a secret chat  has 1h TTL, the messages must be deleted from the encrypted message db within one our. In addition, the secret chat messages should be encrypted properly (using the per-secret-chat encryption scheme).

**Comment by KAMiKAZOW** [comment]
Cutegram is a Telegram client. As far as I see it Telegram also does not encrypt its local storage – at least /storage/emulated/0/Android/data/org.telegram.messenger/cache is not encrypted on Android.

The points about desktop integration by @realbardia are very good. This offers real usability benefits for users instead of snake oil db encryption.

**Comment by xkill** [comment]
A quick solution could be to set secret chat as not stored by default. And warn the user if they change to "store this chat". But better if the app allows the user to set an encryption password to cipher the messages prior to store it on the database.

Why I think that encrypt the messages is not a good solution:

1) If the messages are encrypted on the DB, the app should know the encryption key to decrypt it, so anybody/app with access to DB could have access to the key too.
 - So to encrypt the DB is secure if the encryption key is asked to user prior to decrypt the messages. It could be stored in memory, but after the app is closed or the phone rebooted the app must ask for the key again and avoid to store it anywhere.

2) Encrypt the disk. Only useful if you lost the phone and the "hackers" have your phone switched off. All the apps could access to the encrypted data without asking/knowing the encryption key. Transparent for the user and for the apps, so it does not protect against data leakages via malware, ... (the common way to retrieve data from phones, which are usually running and on)

3. Don't encrypt anything. Ok. Best solution for anyone who does not matter the security. But, if anyone wants clear text, she could select public conversations instead private conversations.

**Comment by KAMiKAZOW** [comment]
“A quick solution could be to set secret chat as not stored by default.”
– Please read https://github.com/Aseman-Land/Cutegram/issues/127#issuecomment-120403963 first

**Comment by borjiviri** [comment]
As I said: 
> Regarding "if the other programs don't encrypt stuff means and I don't have to encrypt my stuff" , from my point of view, it's a very poor argument."

I think that it won't hurt to implement stuff better than others do, unless, you want the message db in plaintext for any obscure reason...

**Comment by legion1978** [comment]
well id say that the thing about security regards more the secret chat feature than the regular chat history. i mean SC is about confidentiality, so (from a user POV) [any form of] encryption is to be implemented. this is, regular chat history not encrypted (no confidentiality expected) secret chat encrypted, erased, whatever (confidentiality expected)

**Comment by KAMiKAZOW** [comment]
“you want the message db in plaintext for any obscure reason...”
– Desktop search is not an obscure reason. It's a way more common use case than being hacked. (If you get hacked all the time, you should change your way of doing IT, not ask applications to think for you.)

**Comment by borjiviri** [comment]
go and tell that to David Vincenzetti ...

**Comment by KAMiKAZOW** [comment]
If Cutegram won't impede my ability to search through messages and export them via any sqlite tool of my own choosing, I'll contribute content to Cutegram's documentation how users can protect their data right after I succeeded packaging Cutegram.

**Comment by borjiviri** [comment]
If you don't care about security just use Whatsapp instead of telegram. By the way, Whatsapp encrypts its message db.

**Comment by xkill** [comment]
KAMiKAZOW. If you want clear text conversations, no problem you can use github comments to have conversations, but please, if you want to contribute to an application pretending to be secure. Avoid to use plain text to store the conversations.

**Comment by legion1978** [comment]
its more like "user should be responsible for his own security" .. which makes sense.. but secret chat security must come from the app in the first place. otherwise "secret" wont mean a thing.

**Comment by borjiviri** [comment]
@KAMiKAZOW 
![nsa-seal-of-approval](https://cloud.githubusercontent.com/assets/7076040/8620166/1519a212-271e-11e5-961d-c68a3d7d69f0.jpg)

**Comment by legion1978** [comment]
@borjiviri thats not very productive.. most people dont give a sht about nsa, snowden, whatnot. they dont care about whatsapp or facebook [lack of] security. they want to use an app or not. it says "secret" they assume it is safe. they dont know or care about italian hackers breaking into their pcs. most people use unsecure passwords if any at all. some other share their fking passwords with the world.. for whatever reason. watch John Oliver interview on Snowden and see whats what. 

and back to the point..
its not cutegram job to watch over every user shoulder, but secret chat feature must be secure in some way from the app. thats the least a common user would expect (or care about)

**Comment by borjiviri** [comment]
Yeah, that's my developers we should care about protecting users from the Dick Pic Program ;-)

**Comment by legion1978** [comment]
lel 
but its truly not cutegram's issue for that matter. the thing is that "secret" MUST mean "safe" in any context. and that IS cutegram's issue :)

**Comment by borjiviri** [comment]
yeah, I agree with you :-)

**Comment by KAMiKAZOW** [comment]
Wow, people incapable to encrypt their /home directory now resort to insults… OK, I'm out. Apparently you don't want contributions by me.
I'll also think twice before releasing the package recipes…

**Comment by legion1978** [comment]
wow. what are you 10 years old? jeez ¬¬
noone is insulting (you). but you seem to fail to understand that not everyone has the need for encrypting the entire home folder (or hd) just to use an app. youre using the wrong logic there.

**Comment by Sollex-21412** [comment]
Agree with legion1978

**Comment by legion1978** [comment]
and yeah, that "i wont let ya play with me toys" statement was +very+ 10 year oldish..

**Comment by borjiviri** [comment]
Very 10 year old-ish and also stupid:
```
# cryptsetup status /dev/mapper/crypted-root
/dev/mapper/crypt-home is active and is in use.
  type:    LUKS1
  cipher:  aes-xts-plain64
  keysize: 512 bits
  device:  /dev/sda2
  offset:  4096 sectors
  size:    463415296 sectors
  mode:    read/write
  flags:   discards 
```

**Comment by legion1978** [comment]
point being? i didnt say you were stupid. i implied youre emotional :) which in fact you are -- you just proved it <3

**Comment by legion1978** [comment]
X)) boo boo

**Comment by Sollex-21412** [comment]
Plz guys, be more constructive. Without any "stupid" or not.

**Comment by legion1978** [comment]
well we already made our points.. now devs have to decide what theyll do..

**Comment by legion1978** [comment]
for me: 
regular chat history db > unencrypted
secret chat history db > encrypted (TTLd, mirrored, summoned from the sixth circle, whatever that ensures privacy- as expected)

**Comment by Sollex-21412** [comment]
@legion1978, as I told in https://github.com/Aseman-Land/Cutegram/issues/127#issuecomment-120406978.

**Comment by legion1978** [comment]
exactly

**Comment by borjiviri** [comment]
Agreed

**Comment by Dyras** [comment]
I think legion1978 nailed it. Though I wish encryption worked like this:
If you set a pin code every conversation is encrypted with that code.
If you don't, nothing is encrypted.

Currently I encrypted the folder with Windows NTFS encryption, but that's professional only so most people will never use that.

If Cutegram wants to be security oriented, which I personlly think it should be, then adding encryption is the obvious choice. Secret chats are supposed to be secret.

**Comment by Simulacrux** [comment]
Yeah would go with a mix from Dyras and Legion1978
With Pin everything is encrypted. 
Without secret chats are encrypted in the db, normal chats/messages not, so you could probably search them with other tools.
Nevertheless it would be nice to have a export function for "storing" the history in some sort of normal file. And then with a choise if to export the encrypted stuff too.

**Comment by realbardia** [comment]
Fixed.
Now all messages (normal messages and secret messages) stores encrypted. Also auth file store encrypted and in the kde store in the kwallet.
