### ISSUE TITLE
[Bug] Is chat with non-contacts working?

### ISSUE THREAD

**Issue by filipesaraiva** [Aseman-Land/Cutegram#13]
Hello, I am using Cutegram 2.0.0 from Mageia package. But the problem in chat with non-contacts remains. The history of chat not update and I can not to send message for them. Is there some way how I can to provide a log or something about it? Thanks!

**Comment by realbardia** [comment]
Hi
Yes we have this issue currently. It's because libqtelegram we use in our packages.
We'll fix it in the next minor release.
Thank you for reporting

**Comment by realbardia** [comment]
Fixed :)
