### ISSUE TITLE
Cutegram parses text like "/test" as a link to a website

### ISSUE THREAD

**Issue by gim-** [Aseman-Land/Cutegram#151]
When I, for example, send something like "/test" to someone and click it, Cutegram opens up the link "http://www.test.com" in the web browser. "/test/test" results in "http://www.test.com/test". Instead, it should not parse it as a link at all with the exception when "/test" is used as a command to a bot. Clicking on it should send this very same command again.
![](http://storage2.static.itmages.com/i/15/0813/h_1439457676_9361503_7cb83644b7.png)

**Comment by gim-** [comment]
Looks like regular expression in the [code](https://github.com/Aseman-Land/Cutegram/blob/79fc6b0ab9d08074c52ecf49b41762a5dfb84b64/Cutegram/asemantools/asemantools.cpp#L126) needs some improvements:
```
((?:(?:\w\S*\/\S*|\/\S+|\:\/)(?:\/\S*\w|\w))|(?:\w+\.(?:com|org|co|net)))
```
This will not only parse "/test" as a link, but also it will fail to accept third-level domains like "bbc.co.uk" and domains from DNS zones other than **com**, **org**, **co** and **net**.
![](http://storage3.static.itmages.com/i/15/0813/h_1439458329_9864936_a3231382f7.png)

**Comment by realbardia** [comment]
Hi... thank you for reporting.
Fixed :)
