### ISSUE TITLE
Secret chat shows unread message - Can't see anything in the chat

### ISSUE THREAD

**Issue by Dyras** [Aseman-Land/Cutegram#153]
Hi. Whenever I start Cutegram I can see that I have 1 unread message from a secret chat conversation. When I click the chat I see absolutely nothing new.

I asked the person, and she has sent 3 new messages.

**Comment by realbardia** [comment]
Hi... thank you for reporting.
Fixed :)

**Comment by Dyras** [comment]
@realbardia So... When is this new version being pushed out? Just wondering, because the lack of secret chat is really irritating
