### ISSUE TITLE
IME cannot work at GNOME 3.14

### ISSUE THREAD

**Issue by tonghuix** [Aseman-Land/Cutegram#16]
I use ibus-pingyin for Chinese input, but it cannot use in GNOME 3.14 in cutegram. Others app works fine.

OS: Debian Jessie
GNOME 3.14.1

**Comment by realbardia** [comment]
Hi

Is another Qt5 apps works without problem? I think it's Qt5 bug.
Anyway We'll check it and will try to fix it.

Thank You for reporting
Bardia Daneshvar
Aseman Team

**Comment by tonghuix** [comment]
well, no others QT

**Comment by Catofes** [comment]
I use fcitx with sunpinyin. Everything worked good.

Archlinux.
GNOME Shell 3.16.2.
cutegram: 2.3.0

I think you may need some addons for ibus to make it work uder qt5. Like fcitx I need 

community/fcitx-qt5 1.0.2-1 [已安装]
    Qt5 IM Module for Fcitx
 
and for ibus I think you need install 

community/ibus-qt 1.3.3-3
    IBus qt library and IBus qt input method plugin

**Comment by adrianiainlam** [comment]
No repro on Ubuntu 14.04.2 with Unity.
Make sure you have the ibus-qt or ibus-qt4 or similar packages installed.
Then in `.bashrc` add the following lines:

    export GTK_IM_MODULE=ibus
    export XMODIFIERS=@im=ibus
    export QT_IM_MODULE=ibus
    export XIM_PROGRAM=/usr/bin/ibus-daemon

**Comment by tonghuix** [comment]
By install ibus-qt5, all works fine. Thank you @all !
