### ISSUE TITLE
Can't see sticker set I added on Telegram Web.

### ISSUE THREAD

**Issue by s8321414** [Aseman-Land/Cutegram#160]
As title says, I can't see my sitcker set added on Telegram Web, maybe it's a bug?

**Comment by KAMiKAZOW** [comment]
Apparently already fixed: https://github.com/Aseman-Land/Cutegram/commit/1289ec24f0bb04786d5a406f43a1c179dc017803

**Comment by s8321414** [comment]
Oh, thanks! Hope it will be including in new release soon.

**Comment by s8321414** [comment]
\o/

**Comment by KAMiKAZOW** [comment]
Updated Cutegram and the libtelegram* dependencies. Still can't see them.
