### ISSUE TITLE
Hidden links and weird interaction.

### ISSUE THREAD

**Issue by alexbenic** [Aseman-Land/Cutegram#162]
##### 1.Left-click in one of the circles or near it. 
![1](https://cloud.githubusercontent.com/assets/7696305/10034485/55db4730-6191-11e5-894d-9a099730fab9.png)

##### 2.Double-click inside green box. Fast.
![2](https://cloud.githubusercontent.com/assets/7696305/10034381/4d9a148a-6190-11e5-914c-c44c4ad913b0.png)

##### 3.
**Green circle** - https://github.com/realbardia ==> Opens in browser.
**Blue circle** - https://github.com/Sollex-21412 ==> Opens in browser.
**Near X** - https://github.com/ineptant ==> Opens in browser.

Try few places of left-click (first step) if you can't replicate bug on the first try.

**Comment by realbardia** [comment]
Hi... thank you for reporting.
Fixed :)
