### ISSUE TITLE
User-defined path to profile location?

### ISSUE THREAD

**Issue by dmitrydonskih** [Aseman-Land/Cutegram#167]
Another option that seems very useful to me - add an option to select location of user's profile (and maybe some other settings related to program behavior on startup, before database is loaded). Maybe ini-file or command-line parameter. This could simply turn program to portable, running from usb stick on different PCs.
Sorry if it is already implemented, I've searched and couldn't find out.

**Comment by realbardia** [comment]
Hi... Thank you for suggestion.
This feature added. You can run cutegram in portable mode using --portable command line flag.

**Comment by sergeevabc** [comment]
> This feature added. You can run cutegram in portable mode using --portable command line flag.

But prior to using that switch, user is obliged to run installer which pollutes system, doesn’t it?
