### ISSUE TITLE
Super annoying: Conversations are automatically muted

### ISSUE THREAD

**Issue by Dyras** [Aseman-Land/Cutegram#173]
Hello. I've noticed something really fascinating with the latest version. Every chat except my one secret chat is automatically muted, with no notifications whatsoever. Whenever I turn on the "sound" again, the notifications still aren't appearing.

**Comment by Lerentis** [comment]
I have the same problem with group chats. 
everytime the left list is updated (new message) two groups are getting muted

**Comment by realbardia** [comment]
Fixed. Thank you for reporting...
