### ISSUE TITLE
Unable to install cutegram on Ubuntu Trusty from PPA due to broken dependency on "ffmpeg"

### ISSUE THREAD

**Issue by LenzGr** [Aseman-Land/Cutegram#18]
I used the following Ubunutu PPA to install Cutegram on my Ubuntu 14.04.2 "trusty" system (x86_64):
```
% cat /etc/apt/sources.list.d/aseman-desktop-apps-trusty.list
deb http://ppa.launchpad.net/aseman/desktop-apps/ubuntu trusty main
# deb-src http://ppa.launchpad.net/aseman/desktop-apps/ubuntu trusty main
```
However, I can no longer install from this repository, as the last version depends on "ffmpeg":
```
% sudo apt-get install cutegram                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cutegram : Depends: ffmpeg but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by realbardia** [comment]
Hi
Fixed.
Thank you for reporting

On Monday, March 30, 2015, Lenz Grimmer <notifications@github.com> wrote:

> I used the following Ubunutu PPA to install Cutegram on my Ubuntu 14.04.2
> "trusty" system (x86_64):
>
> % cat /etc/apt/sources.list.d/aseman-desktop-apps-trusty.list
> deb http://ppa.launchpad.net/aseman/desktop-apps/ubuntu trusty main
> # deb-src http://ppa.launchpad.net/aseman/desktop-apps/ubuntu trusty main
>
> However, I can no longer install from this repository, as the last version
> depends on "ffmpeg":
>
> % sudo apt-get install cutegram
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
>
> The following packages have unmet dependencies:
>  cutegram : Depends: ffmpeg but it is not installable
> E: Unable to correct problems, you have held broken packages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Aseman-Land/Cutegram/issues/18>.
>


-- 
Sent from Mobile

**Comment by participante0** [comment]
It can be installed, but when I run it, I can not see the contents inside the window. I can not use Cutegram installed from the ppa in Linux Mint 17.1 (updated). The `cutegram-2.1.1-ubuntu-amd64.deb` package works fine.

**Comment by participante0** [comment]
![screenshot from 2015-03-31 13 12 55](https://cloud.githubusercontent.com/assets/10296795/6923508/944346a8-d7a8-11e4-8a68-db160c13d59b.png)

`cutegram 2.1.1aseman4-trusty` from the ppa. Behind the window was open Firefox.

**Comment by realbardia** [comment]
Hi...
Can you send console output?
Thank you for reporting :)

**Comment by participante0** [comment]
Hi. Yes, here it is:
```
$ cutegram
QQmlComponent: Component is not ready
"file:///usr/share/cutegram/themes/MamanDooz.qml:2 module "QtQuick" is not installed
" 
qrc:/qml/Cutegram/main.qml:1:1: module "QtQuick" is not installed 
QVariant::load: unable to load type 1142.
QVariant::save: unable to save type 'QJSValue' (type id: 1142).

```

I tried also...
```
$ sudo apt-get install qtquick
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qtquick
```
Thanks you for your work.

**Comment by participante0** [comment]
Thanks, it works now (`cutegram 2.1.1aseman5-trusty`).

**Comment by realbardia** [comment]
Your welcome :)
