### ISSUE TITLE
messages with "<" and ">" characters don't display correctly

### ISSUE THREAD

**Issue by majewsky** [Aseman-Land/Cutegram#184]
I sent the message `</tldr>` using Cutegram 2.7.0, and it was rendered back like this:

![screen12](https://cloud.githubusercontent.com/assets/24696/10870578/78d1fbc4-80ce-11e5-9caa-7fca9ea4b9f8.png)

On Telegram for Android, the message is rendered correctly (without XML entities).

**Comment by realbardia** [comment]
Fixed. Thank you for reporting :)
