### ISSUE TITLE
"Empty" chat, which can't be deleted

### ISSUE THREAD

**Issue by scrobbleme** [Aseman-Land/Cutegram#187]
Hello,

I've an open secured chat, with no real participant (no username, phone number) and am not able to delete it.

![2015-11-19 08_40_51-microsoft edge](https://cloud.githubusercontent.com/assets/504835/11265095/ab12be1a-8e99-11e5-86cf-97fccc38b60d.png)

Are there any log files, which may help or can I create some?

**Comment by xavihernandez** [comment]
Issue aready discussed in #175 
Fix will be in next minor releas (has been answered 26 days ago)

**Comment by scrobbleme** [comment]
Ah, thanks. I used the search, but obviously with other keywords ;) 
So will wait for the next version.
