### ISSUE TITLE
Can't enter my number because it starts with 0

### ISSUE THREAD

**Issue by TheBlackViper1996** [Aseman-Land/Cutegram#188]
As the title suggests I cannot input my number to log in as it won't let me enter a number that starts with 0

**Comment by farseerfc** [comment]
My experience is that you can normally emit that leading 0 if you prefix it with a global country calling code (those start with "+" sign). My telegram official clients accept both format with/without the 0, and send SMS to my phone.

**Comment by TheBlackViper1996** [comment]
I omitted the 0 but now the stickers won't work

**Comment by farseerfc** [comment]
I guess the stickers problem should be another (unrelated) issue. I am not the developer so I can not confirm that. Please look at https://github.com/Aseman-Land/Cutegram/issues/177 .
Btw what is your version of cutegram and OS (distribution)?

**Comment by realbardia** [comment]
Fixed.
Thank you for reporting
