### ISSUE TITLE
Not syncing history, not sending messages

### ISSUE THREAD

**Issue by thermatk** [Aseman-Land/Cutegram#19]
Affects only those who are not in contact list. When I open a conversation with them it starts endless sync, messages never get there and answered.
Fo example, there is a bot (telerobot, tg://resolve?domain=telerobot) who answers the weather if one sends him "погода москва"
Nothing happens here, endless sync + endless sending
![2015-03-31 11 00 54](https://cloud.githubusercontent.com/assets/2287483/6914722/1239e4b2-d796-11e4-9323-977f7a559c81.png)

**Comment by realbardia** [comment]
Hi
Yes... We have some issue because of a bug on libqtelegram.
We'll check it and fix it soon.
Thank you for reporting.

**Comment by realbardia** [comment]
Fixed :)
