### ISSUE TITLE
Voice Message support

### ISSUE THREAD

**Issue by cb88** [Aseman-Land/Cutegram#20]
It seems that there is no voice message support on any of the desktop apps.  Also from what I gather it is just opus audio at a specific bitrate there'd just need to be a button to record and send it. 

In my experience this is one of the more fun features :)

Looks like it just needs to be opus audio for widest support... https://github.com/DrKLO/Telegram/issues/809 So I imagine this would require buildsing ffmpeg with opus support or using libopus directly which I think is what mobile clients do.

**Comment by realbardia** [comment]
Hi
Thank you for good suggestion.
We'll add this feature in the next release.

**Comment by realbardia** [comment]
Added :)
