### ISSUE TITLE
No icon in tray on Mint 17 (Ubuntu) + XFCE

### ISSUE THREAD

**Issue by m00nk** [Aseman-Land/Cutegram#21]
No icon is in tray on Mint 17 (Ubuntu) + XFCE

**Comment by realbardia** [comment]
It's look like an issue, some one report using email some times ago.
I couldn't find that email. But he found a solution to fix it. It's seems its a problem on gnome.
I'll send solution here...
Thank you for reporting

**Comment by realbardia** [comment]
What package you are using? PPA or Our binary packages?

**Comment by m00nk** [comment]
I'm using cutegram-2.1.1-ubuntu-amd64.deb downloaded from page http://aseman.co/en/products/cutegram/

**Comment by thermatk** [comment]
No tray icon visible on Arch Gnome Shell 3.14 too.
Seems to be the same Qt-related issue that happened with Dropbox in December, they fixed it, so it's possible :)

**Comment by dongfengweixiao** [comment]
arch Gnome 3.16 too

**Comment by thermatk** [comment]
There are rumors that Qt 5.5 will fix this.
Also affected are Dropbox, who did something but it still happens, and many others
Example: https://github.com/nitroshare/nitroshare-desktop/issues/37

**Comment by thermatk** [comment]
Could you please provide a build with Qt 5.5 to try it out?

**Comment by realbardia** [comment]
I tried yesterday. Cutegram had some bugs with Qt 5.5. I should fix them first.
But It's seems tray icon problem is fixed. I'll fix problems with Qt 5.5 and provide a build soon.

**Comment by swordfeng** [comment]
it is fixed on gnome for me.

**Comment by tonghuix** [comment]
still no tray icon on GNOME 3.16

**Comment by swordfeng** [comment]
@tonghuix try installing all libraries about appindicator
I've got
libappindicator-gtk2 12.10.0-5
libappindicator-gtk3 12.10.0-5
libappindicator-sharp 12.10.0-5
sni-qt 0.2.6-3
on my Archlinux with Gnome 3.16.2-1

**Comment by thermatk** [comment]
Installing appindicator binaries is not a fix, it's just changing the type of output for Cutegram. Libappindicator is not available everywhere, gets broken often if it's not Ubuntu Unity and so on, it's a workaround.
Still no tray icon on Gnome 3.16.2 Arch with Cutegram 2.4.0

**Comment by farseerfc** [comment]
No problems for systray icons here. Notifications go to notification area of gnome properly.
![2015-06-12 18-13-53](https://cloud.githubusercontent.com/assets/861563/8127083/1e17d7f8-112f-11e5-86af-dbf84dcc8666.png)

Archlinux, Cutegram 2.4.0, Gnome 3.16.2
None of the indicator libraries is installed. No libappindicator*, no sni-qt.

```
archlinuxcn/cutegram 2.4.0-1 [installed]
aur/cutegram 2.4.0-1 [installed]
```
I installed the binary package from [archlinuxcn] repo, but it should be the same as the aur package.
(I can ensure that as both packages are maintained by me).

**Comment by tonghuix** [comment]
I test it in Debian 8, with GNOME 3.14 and installed libappindicator, no icon.

**Comment by franciskittu** [comment]
I'm in Debian 8 GNOME 3.14, I've seen the tray icon accidentally 5 times so far, so I know that it's a white icon :) .

Seriously, I don't know why but once every 100 it appears.

**Comment by farseerfc** [comment]
@tonghuix @franciskittu it might be this bug in qt5 that got fixed in qt 5.4.2 ?
https://bugreports.qt.io/browse/QTBUG-43859
Archlinux had this fix since Jun 3rd, just 9 days ago.

**Comment by tonghuix** [comment]
Another note is shadowsocks-qt5 works fine in Debian 8 GNOME 3.14.

**Comment by farseerfc** [comment]
@tonghuix https://github.com/librehat/shadowsocks-qt5/issues/66
they had the same bug, and they are suggested to depend on appindicator https://github.com/librehat/shadowsocks-qt5/issues/66#issuecomment-103555725 through this change
https://github.com/librehat/shadowsocks-qt5/commit/7ef006f307ab37ef67daba1dd020abd4be8d0a0d
.

**Comment by tonghuix** [comment]
I use topicon extension, here is my topbar of GNOME 3.14 in Debian 8. 
The green icon is shadowsocks-qt5, and black blank should be the Cutegram icon.
![2015-06-12 19-37-36](https://cloud.githubusercontent.com/assets/423703/8129315/aba2c9a6-113a-11e5-91f6-dfc192946a25.png)

**Comment by thermatk** [comment]
The bugfix on Qt side that @farseerfc suggested might be it, I'll have to wait for new packages to land on my machine.
Could you test that Nitroshare, for example, got also fixed?

**Comment by swordfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/5018356/8134043/bc6d1682-115e-11e5-9fda-283a5d4af4fe.png)

@thermatk Is it like that?

**Comment by thermatk** [comment]
Ok, I completely agree, this is finally fixed upstream! :)
I too got Cutegram and Nitroshare icons to work.
Ubuntu users will be happy getting these updates in 15.10 xD
