### ISSUE TITLE
doesn't work with Qt5.6.x

### ISSUE THREAD

**Issue by ahjolinna** [Aseman-Land/Cutegram#223]
I cant get cutegram to compile with Qt5.6 on chakraOS, and the precompiled version (with Qt5.5.x) doesn't work it just crashes at least if u try to "login" ..I cant get futher than that

**Comment by farseerfc** [comment]
Running Cutegram 2.7.1 with Qt5.6.0 on Arch Linux without any problems.
See: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cutegram

**Comment by ahjolinna** [comment]
telegramqml, libqtelegram-ae and cutegram build/compile fails for me, using both arch and chakra's pkgbuild

also this is the [chakras pkgbuild](http://git.chakraos.org/desktop.git/blob/d373859d9bbc8e6df8e28537f21abff31572c3c4:/cutegram/PKGBUILD) 

all the compile errors I had was something about qt5, and there was a lot

**Comment by farseerfc** [comment]
I mean, this is a packaging issue and should be addressed in chakra, not upstream.

**Comment by ahjolinna** [comment]
apprently the problem was on my system not chakra...and why I couldnt login was because there is not password support in cutegram...but there was no indication about this..error or something..so it was hard to see that...oh well..fuck this
