### ISSUE TITLE
Authentication needed on every start / cutegram loses its settings on exit

### ISSUE THREAD

**Issue by doktor5000** [Aseman-Land/Cutegram#24]
Hi,

seems I need to authenticate every time cutegram starts. That is probably not expected ... ?

Also, everytime I quit cutegram, it loses its settings. Could this be some permission issue, and how to troubleshoot that? Where should cutegram store its settings? Only in ~/.config/Cutegram ?

**Comment by realbardia** [comment]
Hi
Yes, All settings store on .config/Cutegram location.
Something like this:
~/.config/Cutegram/camera
~/.config/Cutegram/profiles.sqlite
~/.config/Cutegram/+123456789
~/.config/Cutegram/+123456789/auth
~/.config/Cutegram/+123456789/config
~/.config/Cutegram/+123456789/userdata.db
~/.config/Cutegram/+123456789/secret
~/.config/Cutegram/+123456789/database.db
~/.config/Cutegram/config.ini

Can you send cutegram console output here?
Thank you for reporting :)

**Comment by doktor5000** [comment]
Oo ...

This is really weird, started it today, no authentication required and it even displays the history for all my chats, no issues so far. 

Only output that is shown in console is
`libpng warning: iCCP: known incorrect sRGB profile`
which is a known issue with the stricter checking from recent libpng versions: https://bugzilla.redhat.com/show_bug.cgi?id=1036321
and upon exit it shows
`Xlib:  extension "NV-GLX" missing on display ":0".` which might be an issue with some recent nvidia driver or kernel update.

Will provide feedback if this issue reoccurs.

**Comment by realbardia** [comment]
I made some changes to source code to fix this problem. Cutegram had some bugs on database.

**Comment by bullgates** [comment]
Hello, I'm having the same issue. Is there any easy fix for this? Thanks

**Comment by realbardia** [comment]
Hi.
What is you operating system? and If you are using linux what is your distro and What package installed on your system?

**Comment by bullgates** [comment]
Hi realbardia
I have Manjaro Linux and cutegram is the version 2.7.0, built from the AUR from Arch Linux. It was working properly until 3 days ago that I have to login with a new SMS everytime. I'lltry to use the git version to see if it helps.
Thanks.

**Comment by bullgates** [comment]
Hello realbardia, I've installed the latest git version but still the problem appeared, so I've deleted all the configuration, after a new fresh start the issue seems to be gone. Just sharing the solution since it can help someone. Thanks!

**Comment by silberzwiebel** [comment]
I'm facing this issue, too. I'm using Fedora 22 with GNOME, and have installed Cutegram 2.7.0 from [this copr repo](https://copr.fedoraproject.org/coprs/heliocastro/cutegram/).

Starting cutegram from the command line with the -V option gives absolutely no output, I've also deleted the ~/.config/Cutegram folder as suggested, but still need to fill in a new code everytime. I do not have an auth file in my config folder, though, as mentioned above. Maybe that's the problem?

**Comment by bullgates** [comment]
Well the problem just returned for me also... I have to authenticate by sms again.

**Comment by doktor5000** [comment]
FWIW I also had this issue sometimes with the official telegram client after enabling two-factor authentication. But it's only intermittently, but across linux, windows and android. Currently it's working normally.

**Comment by toothstone** [comment]
I'm also running into this, output doesn't tell me anything. Any recommendations?

**Comment by vital-edu** [comment]
Same problem happens with me.
Using Arch Linux, cutegram-2.7.1-3.

**Comment by bullgates** [comment]
Although I liked cutegram a lot, I had to uninstall it and install the official Telegram Client because of this.
`yaourt -S telegram-desktop`

**Comment by MarceloSaied** [comment]
yaourt -S telegram-desktop
==> Downloading telegram-desktop PKGBUILD from AUR...
==> ERROR: telegram-desktop not found in AUR.

manjaro 16 xfce
