### ISSUE TITLE
I can't enter to aseman.co

### ISSUE THREAD

**Issue by participante0** [Aseman-Land/Cutegram#25]
...Since Saturday April 11. Which is the reason? Closed for maintenance? Are they going to change the domain name? Is it the end for aseman-land?

**Comment by realbardia** [comment]
Hi
No... Our server damaged because of Data center mistakes.
We are moving to new server and new data center. Site is up now, But not completely.
We are working on it to fix all problems today.
Thank you

**Comment by legion1978** [comment]
actually website has been down for a while now-- thought the project was dead
