### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Kastilo** [Aseman-Land/Cutegram#250]
Hello there,

I am trying to use cutegram but it seems it doesn't work, I enter the code and it keeps failing, anything you know of??

**Comment by wizzard0** [comment]
Certainly cannot login if 2-factor verification is enabled

**Comment by deriherdianto** [comment]
@wizzard0  ah.. thank you.. that solve my problem

**Comment by Abbode** [comment]
why can't login with 2-steps authentication is enabled ???? please fix that :\

**Comment by FTOH** [comment]
+1

**Comment by Twente-Mining** [comment]
such crap
