### ISSUE TITLE
Cutegram binary built from AUR does not run on Manjaro

### ISSUE THREAD

**Issue by rodneyrod** [Aseman-Land/Cutegram#253]
Steps to reproduce:
1. Install Manjaro
2. Install aseman-qt-tools-git from AUR
3. Install cutegram-git from AUR

Program compiles and installs just fine, but when trying to run the binary it just hangs and produces no output in the terminal, have to ctrl+C it to force it to close. 
cutegram --help also produces the same result, no output.

**Comment by farseerfc** [comment]
You didn't mention which `libqtelegram-ae` or `telegramqml` were you using. Please also install `libqtelegram-ae-git` and `telegramqml-git` from AUR.

**Comment by rodneyrod** [comment]
Ahh okay, I was using whatever provided version of telegramqml is provided by Manjaro, not sure about the -ae-git but I'll check up on that when I get home.

Isn't there some way you can detect the versions of these libraries and prevent them from compiling with older versions?

**Comment by farseerfc** [comment]
Yes I can/should specify depends on libqtelegram-ae-git and telegramqml-git in AUR. They used to be compatible with non `-git` version but not compatible for now. This is a AUR packaging issue and should be reported to AUR. Either way I will fix them in AUR soon.

**Comment by rodneyrod** [comment]
Excellent, that would be greatly appreciated.

Another issue on my system, the Cutegram AUR requires aseman-qt-tools to be installed, which is provided by aseman-qt-tools-git but for whatever reason by default it looks for a package called aseman-qt-tools, which it can't and then fails as unresolved dependency.

Also I think the versioning on aseman-qt-tools-git needs fixing, I installed it last night and immediately after Octopi labelled it as being out of date.

**Comment by rodneyrod** [comment]
On a side note I would be prepared to submit changes to AUR directly, but they don't really make it easy to extract a version number from --HEAD.

**Comment by farseerfc** [comment]
Fixed in https://aur.archlinux.org/cgit/aur.git/commit/?h=cutegram-git&id=b8342915ac8793d3efac495e915b3b6020e55cab

**Comment by rodneyrod** [comment]
Thanks so much for that, I'll test it out as soon as I get home. and let you know how it goes.

**Comment by rodneyrod** [comment]
Everything works, closing this issue.

On a side note, there's no .desktop file included with Cutegram for some reason.
