### ISSUE TITLE
No way to add a contact?

### ISSUE THREAD

**Issue by mozmck** [Aseman-Land/Cutegram#27]
I could not find any way to add a contact in Cutegram, and had to use Telegram to do it.

**Comment by ineptant** [comment]
Yes! there isn't, but we are working on it. Thank you for suggestion.

**Comment by ineptant** [comment]
Yes! there isn't, but we are working on it. Thank you for suggestion.

**Comment by ineptant** [comment]
Yes! there isn't, but we are working on it. Thank you for suggestion.

**Comment by ineptant** [comment]
Done.
