### ISSUE TITLE
[Bug] Cutegram font's problem in debian wheezy 32.

### ISSUE THREAD

**Issue by namoplasta** [Aseman-Land/Cutegram#28]
![fonts](https://cloud.githubusercontent.com/assets/5007575/7245885/3f8f4e86-e7ca-11e4-934d-87526447033b.png)

How fix this?

**Comment by ineptant** [comment]
What's your default font? :)

**Comment by namoplasta** [comment]
How see default font?
I do not set anything in cutegram, just installed and stayed that way.

**Comment by namoplasta** [comment]
$ dpkg-reconfigure fontconfig-config
I set as autohinter, always, no.

This?

**Comment by realbardia** [comment]
No... I mean desktop font.
If you have dconf installed and using gnome, you can see using below command:
dconf read /org/gnome/desktop/interface/font-name
Or using gnome-tweak-tools
And in KDE from systemsettings

**Comment by realbardia** [comment]
Can you send cutegram console output here?
Thank you for reporting

**Comment by namoplasta** [comment]
Hi, not appear output when run cutegram in terminal, I'm using debian with LXDE instead KDE or Gnome.

**Comment by namoplasta** [comment]
See fonts LXDE here?
![lxde](https://cloud.githubusercontent.com/assets/5007575/7268221/459203a4-e89d-11e4-9652-871e174d0a24.png)

**Comment by realbardia** [comment]
OK... Thank you, Fonts are ok, We'll check it on the debian lxde and fix it soon :)

**Comment by namoplasta** [comment]
Hi, I instaled a new version debian (8, jessie), now work fine.
