### ISSUE TITLE
gtk warning   : ) 

### ISSUE THREAD

**Issue by Z-Y00** [Aseman-Land/Cutegram#284]
i got this app from the http://aseman.co/en/products/cutegram/
and the gdebi-gtk give me the following :

(gdebi-gtk:4100): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(gdebi-gtk:4100): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(gdebi-gtk:4100): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

maybe you can update those thing ;)
hoping this would be easy

**Comment by andrew-phi** [comment]
Why are there any GTK dependencies in a QT-based project anyway??
Could not install cutegram because of libappindicator1, gstreamer, etc. :(

**Comment by Z-Y00** [comment]
Hi,It seems that this app is no longer maintained:)
maybe you should switch to other apps
