### ISSUE TITLE
[Feature Request] Support AT username and reply

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#30]
The tdesktop client and webapp of telegram supported these features:
- [ ] AT(@) username
- [ ] reply to a message

**Comment by realbardia** [comment]
Hi
AT feature added to cutegram and will release in the next days.
And about reply feature, Telegram hasn't has public reply API currently yet. So we have 2 choice.
First one is waiting for telegram to publish reply API.
And Second is to read tdesktop source code and extract reply methods from tdesktop source code which needs time.
Both of them takes a lot of time. 
Anyway... We'll add this feature in the future.

**Comment by farseerfc** [comment]
Hi
Thank you. I am looking forward to the future release!

**Comment by realbardia** [comment]
Reply feature also added
