### ISSUE TITLE
Please port audio output to gstreamer1.0 OR Qt phonon

### ISSUE THREAD

**Issue by SanKro** [Aseman-Land/Cutegram#37]
right now cutegram uses gstremer0.10 for audiooutput (voicemessages). 0.10 is depricated and nobody installs it by default anymore.

for example when you run kubuntu 15.04 this feature wont work, because the plugin gstreamer0.10-plugins-bad isnt installed...

now there are 2 things you could do -> port is to gspreamer 1.0 diretly or port it to qt phonon (should be used by the qt multimedia framework by default)

**Comment by realbardia** [comment]
Qt 5.5 now supports Gstreamer 1.0. Now cutegram supports gstreamer 1.0, if it build using Qt 5.5 :)

**Comment by SanKro** [comment]
Thank you :) .. will you provide it in the PPA when 5.5 is in wily (*buntu 15.10?)
