### ISSUE TITLE
[Bug] Participants list grid size don't change with DPI settings

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#38]
I have a screen of 138 DPI and KDE5 auto-configured it for me. With this setting, the participants list get crowded with icons overlapping each other. A workaround will be setting DPI to 96 currently.

Here is a screenshot made on my laptop:
![Screenshot](https://img.vim-cn.com/ae/c19bb2527fc80dd28ac27bac0b019e70876117.png)

The other part of the UI works great under 138 DPI, so I guess there will be a solution to this problem.

My configuration:
- Cutegram 2.2.0-stable
- Archlinux
- KDE Plasma 5.3
- qt5 5.4.1

**Comment by realbardia** [comment]
Hi...
Thank you for reporting.
Fixed :)
