### ISSUE TITLE
Cutegram 2.2.1 stopped working

### ISSUE THREAD

**Issue by serge1peshcoff** [Aseman-Land/Cutegram#45]
Before this I had 2.2.0 and everything was working fine.
Now I upgraded to 2.2.1 and when the program starts, it freezes like this:
![snapshot16](https://cloud.githubusercontent.com/assets/1060257/7682186/e14a3e56-fd7e-11e4-98b3-4f3a8ae8140a.png)

Terminal output shows this:

	QVariant::load: unable to load type 1208.
	QVariant::save: unable to save type 'QJSValue' (type id: 1208).

	QVariant::load: unable to load type 1208.
	QVariant::save: unable to save type 'QJSValue' (type id: 1208).

	QVariant::load: unable to load type 1208.
	QVariant::save: unable to save type 'QJSValue' (type id: 1208).

and so on.
OS: Linux Mint 17 w/KDE.

**Comment by realbardia** [comment]
Hi
Please remove auth file from: ~/.config/Cutegram/[PhoneNumber]/auth and try again.
If not works again, please tell me what package installed on your system? (launchpad ppa, our deb package or our binary (installer) package)
Thank you for reporting :)

**Comment by pdf** [comment]
Confirmed, from the PPA `2.2.1-2aseman-vivid`, connects fine on first run, but subsequent launches just sit at the loading spinner.  Logging out and back in again makes it work, as does deleting the config directory.

**Comment by SanKro** [comment]
same for me with 2.2.1. when i sign in everything is fine. close (not just minimize to tray) the app and restart is leads me to this screen up ...

a 10 secounds strace cutegramm shows:
https://paste.kde.org/plw9cvqpq

kubuntu 15.04 -> your ubuntu ppa

**Comment by realbardia** [comment]
Hi
I have made some changes on cutegram to fix this problem. Please check our daily ppa.
Thank you all for reporting :)

**Comment by SanKro** [comment]
daily ppa works for me again :)

**Comment by pdf** [comment]
:+1:
