### ISSUE TITLE
Please tag 2.3.0 stable release

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#48]
From commit log and released changelog I can see a 2.3.0 is available for Linux, but I cannot find any tagged 2.3.0 release here.
I am maintaining a cutegram package for archlinux, a tagged release will help me release a stable version for archlinux user.
Thank you very much

**Comment by buschmann23** [comment]
+1
Same for me on openSUSE.

**Comment by realbardia** [comment]
Hi
Done on Cutegram (2.3.0) and libqtelegram-ae (3.3)
