### ISSUE TITLE
Startloop

### ISSUE THREAD

**Issue by Lerentis** [Aseman-Land/Cutegram#52]
First of all I want to mention that this is the most beautiful telegram client I have seen so far :D

I'm having some issues thou:

On Windows the Application just hangs in a "bootloop" if i start it a second time (not at the same time. registration was no problem but it just hangs after restart).
I'm running into the same "loop" after i come back from suspend on arch linux.

![bug](https://cloud.githubusercontent.com/assets/3034381/7816752/ff0a5e68-03c7-11e5-8f51-46489939e546.JPG)

Are there some log files i could provide to give you guys more informations about this bug? 

OS Specs 
Windows:
Windows 8 Pro 64-bit
AMD FX-8350

Linux:
Arch Linux x64
GNOME
Intel I7-4710HQ

Keep up the good work!

**Comment by realbardia** [comment]
Hi
Thank you for your kindness.
Windows bug is a known bug, we are working on it. It happened on some devices.

Just console output.
Thank you for reporting.
We'll fix these bugs soon

**Comment by Lerentis** [comment]
Sadly i can not provide any console output on this issue ._.

**Comment by realbardia** [comment]
I found the problem, At least in my system.
The problem is because wrong timezone or clock settings on my operating system. libqtelegram needs correct clock settings.
Is your clock and timezone settings is correct?

**Comment by Lerentis** [comment]
everything is working correctly on that end. scheduled sync via NTP.
still the same beahvior

**Comment by Lerentis** [comment]
SOLVED. 

i still don't know why but i don't have this bug anymore, so I assume it has silently been fixed. keep up the good work (:

**Comment by realbardia** [comment]
Good news.
It's seems it's because many changes on the libqtelegram-ae, we made in the last release :)
