### ISSUE TITLE
Cutegram hangs on startup.

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#54]
Cutegram hangs on startup with:
<pre>
(cutegram:4923): GLib-GObject-WARNING **: cannot register existing type 'GstObject'
(cutegram:4923): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(cutegram:4923): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
(cutegram:4923): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(cutegram:4923): GStreamer-CRITICAL **: gst_element_class_set_details_simple: assertion 'GST_IS_ELEMENT_CLASS (klass)' failed
(cutegram:4923): GStreamer-WARNING **: static caps 0x7f833b28cc90 string is NULL
(cutegram:4923): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(cutegram:4923): GStreamer-WARNING **: static caps 0x7f833b28cc10 string is NULL
(cutegram:4923): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
(cutegram:4923): GStreamer-WARNING **: static caps 0x7f833b28cc90 string is NULL
(cutegram:4923): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
</pre>

System:
Ubuntu 14.04 x64

Built from git.

**Comment by realbardia** [comment]
It's because a conflict between gstreamer and system webkit.
https://github.com/Aseman-Land/Cutegram/issues/41

**Comment by Sollex-21412** [comment]
Yep, it works. Thanks. )
