### ISSUE TITLE
can't display emoticons in name

### ISSUE THREAD

**Issue by hrzhu** [Aseman-Land/Cutegram#55]
If a user's name contains emoticon, cutegram only shows rectangle. Both Android and browser app can display emoticon in name. They show them differently though.

**Comment by farseerfc** [comment]
It can if you have emoji font installed/in-use.
![2015-05-29-131934_209x80_scrot](https://cloud.githubusercontent.com/assets/861563/7876537/67b0e512-0608-11e5-82f4-5e46f46ea96c.png)

**Comment by hrzhu** [comment]
Okay, installing `ttf-ancient-fonts` solve the problem. Thanks for the info.
