### ISSUE TITLE
Message in Detailed List has wrong height when emoji is in the message

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#60]
Steps to reproduce:
1. Enable detailed list
2. Let someone send you a message with emoji. (Or send one to yourself)

That is wrong:
The last message shown in detailed list will only show half of the line.
The line seems to be higher than the display size.

![2015-05-31-214409_354x74_scrot](https://cloud.githubusercontent.com/assets/861563/7901979/714b5c1a-07de-11e5-9106-e1db1532bd7e.png)

My environment:
- Archlinux
- Cutegram 2.3

**Comment by Sollex-21412** [comment]
Seems to me, it has been fixed in https://github.com/Aseman-Land/Cutegram/issues/100.

**Comment by realbardia** [comment]
Yes... Fixed :)
