### ISSUE TITLE
OSX ver multiple context menu

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#64]
Cmd+Click on the messages will have multiple context menu get displayed
![2015-06-07 00 41 36](https://cloud.githubusercontent.com/assets/861563/8020286/2b2130a0-0cae-11e5-9ceb-e964c176a863.png)
And there is no way to dismiss/hide them.

OS: Mac OSX version 10.10.4
Cutegram 2.3

**Comment by realbardia** [comment]
Hi
Thank you for reporting.
Fixed and Will release soon :)
