### ISSUE TITLE
cutegram completely broken with 2.3 & 2.4 (no avatars, no file transmissions, no chats possible)

### ISSUE THREAD

**Issue by SanKro** [Aseman-Land/Cutegram#65]
because of a new phone number i had to delete the old one. so i removed all configs in ~/.config/Cutegram
now i used my new number (already registered via telegram on android)
the first thing i experienced was that there are no avatar (user pictures). next i tried to send a file, but nothing happens. at last i've seen that there are already 10new messeges for my avalable but not a single one poped up in cutegram

console output:
cutegram 
service is "org.kde.StatusNotifierItem-3312-1"
kf5.kiconthemes: "Theme tree: (Breeze)"
Registering a client interface to the KStatusNotifierWatcher
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesGetDialogs(qint32, qint32, qint32): AUTH_KEY_UNREGISTERED"
void TelegramQml::getFile(FileLocationObject*, qint64, qint32) : Can't detect size of:  ChatPhotoObject(0x307c1d0)
void TelegramQml::getFile(FileLocationObject*, qint64, qint32) : Can't detect size of:  ChatPhotoObject(0x307cc40)
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::accountUpdateStatus(bool): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesGetHistory(const InputPeer&, qint32, qint32, qint32): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesReadHistory(const InputPeer&, qint32, qint32, bool): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesGetHistory(const InputPeer&, qint32, qint32, qint32): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesSetTyping(const InputPeer&, const SendMessageAction&): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesSetTyping(const InputPeer&, const SendMessageAction&): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesSetTyping(const InputPeer&, const SendMessageAction&): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesSendMessage(const InputPeer&, const QString&, qint64): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesGetDialogs(qint32, qint32, qint32): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesReadHistory(const InputPeer&, qint32, qint32, bool): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesSetTyping(const InputPeer&, const SendMessageAction&): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesSetTyping(const InputPeer&, const SendMessageAction&): AUTH_KEY_UNREGISTERED"
void TelegramQml::error(qint64, qint32, QString) "qint64 Api::messagesGetHistory(const InputPeer&, qint32, qint32, qint32): AUTH_KEY_UNREGISTERED"
[....]

Kubuntu 15.04
Plasma 5.3.1
Qt 5.4.1
uname -mr -> 3.19.0-18-lowlatency x86_64

**Comment by SanKro** [comment]
same system, back to cutegram 2.1 and everything works again

**Comment by SanKro** [comment]
removed ~/.config/Cutegram again and installed the new cutegram 2.4 everythings broken again
$ cutegram
kf5.kiconthemes: "Theme tree: (Breeze)"
service is "org.kde.StatusNotifierItem-12394-1"
Registering a client interface to the KStatusNotifierWatcher
void TelegramQml::getFile(FileLocationObject*, qint64, qint32) : Can't detect size of:  ChatPhotoObject(0x2ff0ab0)
void TelegramQml::getFile(FileLocationObject*, qint64, qint32) : Can't detect size of:  ChatPhotoObject(0x2ff13d0)
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""
void TelegramQml::error(qint64, qint32, QString, QString) "AUTH_KEY_UNREGISTERED" ""

**Comment by SanKro** [comment]
another interesting fact is:
fresh config (rm -r ~/.config/Cutegram)
when i install cutegram 2.1, start it, log in, then close it and upgrade to 2.4 everything is ok. i can read and send messages, send and recive pictures/files and blah
output (-V)
https://paste.kde.org/p9nkb7k7g

fresh config (rm -r ~/.config/Cutegram)
when i install cutegram 2.3 or 2.4 directly and log in. i cant see pictures, i cant send messages or anything.
output (-V)
https://paste.kde.org/poanaerdl

**Comment by realbardia** [comment]
Hi...
I stopped 2.4 release because of this bug.
Thank you for reporting and Good details about this bug.

**Comment by Sollex-21412** [comment]
+1. I have had same problem =(

**Comment by realbardia** [comment]
My main problem is, This bug doesn't happened on my system or on my friends system. So it's hard to fix. Maybe It happened just on special locations or special system configurations.
Anyway I trying to fix it.

**Comment by Sollex-21412** [comment]
I tried several systems and platform. Real and on virtual machines. And this thing happened everywhere. I played also with time zones. Same result.

**Comment by realbardia** [comment]
I add a feature to Cutegram, you can change default dc-id and default ip address on start. Cutegram uses default dcId and IP address for first login and authenticate process.
So please remove configuration (removing auth file is enough) and try again with below commands.

    cutegram --dc-id 4

And If not working, please test below command too:

    cutegram --dc-id 4 --ip-address 149.154.167.91

Please tell me the results.
Thank you :)

**Comment by Sollex-21412** [comment]
Unknown option 'dc-id'.

**Comment by realbardia** [comment]
Sorry... I forgot to push it to github. now you can also try it using github :)

**Comment by Sollex-21412** [comment]
Strange, but now it won't connect at all. Previous version is OK.

<pre>
Vladimirs-Mac-mini:build vpankratov$ ./cutegram.app/Contents/MacOS/cutegram --dc-id 4 -V
tg.util.utils: public key "/Users/vpankratov/dev/Cutegram/build/build/cutegram.app/Contents/MacOS/../Resources//tg-server.pub" loaded successfully
tg.core.dcprovider: DC 4 ready
tg.core.session: created session with id "fcfce61307099c4b"
tg.core.dcprovider: Api connected to server and ready
tg.core.session: Sending query of size 68 to DC 4 at "149.154.167.91" : 443 by session "fcfce61307099c4b"
tg.core.session: sending message with sha1 "1777777777772504751744"
tg.core.session: msgId is "55758fb500000000"
tg.core.session: connection # 30 received rpc answer -1 with 88 content bytes by session "fcfce61307099c4b"
tg.core.session: server error -1
</pre>

<pre>
Vladimirs-Mac-mini:build vpankratov$ ./cutegram.app/Contents/MacOS/cutegram --dc-id 4 --ip-address 149.154.167.91 -V
tg.util.utils: public key "/Users/vpankratov/dev/Cutegram/build/build/cutegram.app/Contents/MacOS/../Resources//tg-server.pub" loaded successfully
tg.core.dcprovider: DC 4 ready
tg.core.session: created session with id "161a21aa01d3ee0"
tg.core.dcprovider: Api connected to server and ready
tg.core.session: Sending query of size 68 to DC 4 at "149.154.167.91" : 443 by session "161a21aa01d3ee0"
tg.core.session: sending message with sha1 "1777777777770200750551"
tg.core.session: msgId is "5575901800000000"
tg.core.session: connection # 30 received rpc answer -1 with 88 content bytes by session "161a21aa01d3ee0"
tg.core.session: server error -1
</pre>

<pre>
Vladimirs-Mac-mini:build vpankratov$ ./cutegram.app/Contents/MacOS/cutegram -V
tg.util.utils: public key "/Users/vpankratov/dev/Cutegram/build/build/cutegram.app/Contents/MacOS/../Resources//tg-server.pub" loaded successfully
tg.core.dcprovider: DC 2 ready
tg.core.session: created session with id "70642dd21f714ac1"
tg.core.dcprovider: Api connected to server and ready
tg.core.session: Sending query of size 68 to DC 2 at "149.154.167.51" : 443 by session "70642dd21f714ac1"
tg.core.session: sending message with sha1 "1777777777760701643545"
tg.core.session: msgId is "5575912900000000"
tg.core.session: connection # 30 received rpc answer -1 with 88 content bytes by session "70642dd21f714ac1"
tg.core.session: server error -1
</pre>

**Comment by SanKro** [comment]
cutegram --dc-id 4 --ip-address 149.154.167.91 works for me
https://paste.kde.org/pklmnvnev

with cutegram --dc-id 4 i cant connect

my custom system configuration is:
mariadb 10 for mysql
/tmp as tmpfs ;; fstab↓
(tmpfs                                           /tmp            tmpfs   nodev,nosuid            0       0)
german system language and timezone GMT + 2
ipv6 connection, v4 available
google DNS
8.8.8.8
8.8.4.4
2001:4860:4860::8888
2001:4860:4860::8844
thats it

**Comment by realbardia** [comment]
Okey. I update libqtelegram-ae package to. Can you run it without above arguments? Hope to fix.

**Comment by Sollex-21412** [comment]
<pre>
cutegram --dc-id 4 --ip-address 149.154.167.91
</pre>
It works! History, avatars etc. They are working =)

**Comment by SanKro** [comment]
but i still cant send any message and now telegram sometimes just segfaults after startup with the new libqtelegram-ae

**Comment by realbardia** [comment]
I think it was telegram servers problem. I have this problem last night on all my devices and today fixed.
Please check it again. Thank you :)
![20](https://cloud.githubusercontent.com/assets/7826193/8050810/d463cdd6-0e88-11e5-91a7-1c4040d7ce0c.png)

**Comment by Sollex-21412** [comment]
This also fixes #56 =)
