### ISSUE TITLE
Blurry emojis

### ISSUE THREAD

**Issue by legion1978** [Aseman-Land/Cutegram#71]
hi
i dont know.. emojis on the icon select window looks blurry. once sent, in the message window they look a little smaller and sharp. so maybe that small window has the wrong emoji size?

**Comment by realbardia** [comment]
Hi
Checked, It seems yes, It has wrong size.
Thank you. We'll fix it soon :)

**Comment by legion1978** [comment]
cool :)

**Comment by realbardia** [comment]
Thank You for reporting. Fixed and Will release soon :)
