### ISSUE TITLE
Chat list item goes above the first item when replying

### ISSUE THREAD

**Issue by swordfeng** [Aseman-Land/Cutegram#73]
After replying a chat which is not the first item in the list at the time, it goes somewhere above the visible area...
I'm using Cutegram 2.4 on Archlinux.

It goes back if I scroll up and down.

Edit: It also happens when there is a new message received in current chat.

**Comment by swordfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/5018356/8082069/ee111a20-0fac-11e5-93d5-271340821b54.png)
I mean, like this.

**Comment by Sollex-21412** [comment]
+1. Same situation. Very annoying.

**Comment by darkpumpkins** [comment]
+1 on both Windows and linux build :/.

**Comment by realbardia** [comment]
Fixed on the github and Will include on the 2.4.1 release.
