### ISSUE TITLE
Update Screenshots on Official Website

### ISSUE THREAD

**Issue by tonghuix** [Aseman-Land/Cutegram#74]
Just a remind for you. 

Cause 2.3.0 and 2.4.0 added a lot of new feature that changes the UI, so it is better update screenshots on website. so that helping promote this fantastic software.

**Comment by realbardia** [comment]
Hi
We'll change it soon. Thank you.

**Comment by realbardia** [comment]
Updated... But we need slide show to shows all the Cutegram features. Maybe in the future.
Thank you anyway :)
