### ISSUE TITLE
Messages sent to an offline secret chat user are not delivered

### ISSUE THREAD

**Issue by Thunderpig72** [Aseman-Land/Cutegram#76]
Hi, great program etc.

Here's what I did:
I opened up a secret chat with my girlfriend with the latest version of Cutegram. I have Telegram on Android Kitkat.
I wrote to my girlfriend to confirm it's working.

Here's what doesn't work:
When my girlfriend closes Cutegram, any message that I send to her is lost. Messages sent to her when she's online are delivered, however.

Here's what should happen:
The messages should of course be received when she starts Cutegram, instead of the messages being lost.

How to replicate:
1. Start a secret chat with Cutegram
2. Write something to him/her to confirm it's working
3. Close Cutegram
4. Send a message when the user is offline
5. Start Cutegram and notice the message is never received.

Tested with both my girlfriend and another friend. Same thing happens with both.

**Comment by realbardia** [comment]
Thank You for reporting. Fixed and Will release soon :)
