### ISSUE TITLE
Changing sound to *Custom* causes crash on Windows

### ISSUE THREAD

**Issue by Simulacrux** [Aseman-Land/Cutegram#79]
Hi, 
everytime i try to change the notification sounds in Cutegram to *Custom* the application is crashing. My system is a Windows 8.1u1, but it also crashes on my old backup system a Windows 7.
A trial run with Administrator priviliges did not change anything.

The appearing crash dialog shows this error:
>`Problem signature:`
>`Problem Event Name:	APPCRASH`
>`Application Name:	cutegram.exe`
>`Application Version:	1.0.0.0`
>`Application Timestamp:	05d857a0`
>`Fault Module Name:	Qt5Qml.dll`
>`Fault Module Version:	5.4.0.0`
>`Fault Module Timestamp:	073a7bc0`
>`Exception Code:	c0000005`
>`Exception Offset:	00127380`
>`OS Version:	6.3.9600.2.0.0.256.48`
>`Locale ID:	1031`
>`Additional Information 1:	2e10`
>`Additional Information 2:	2e10af995511aacc804b619032d3afdb`
>`Additional Information 3:	3dfa`
>`Additional Information 4:	3dfa384889af578b90680f04015d35f4`

In the Eventlog this info message shown:
>`Fault bucket , type 0`
>`Event Name: APPCRASH`
>`Response: Not available`
>`Cab Id: 0`
>`Problem signature:`
>`P1: cutegram.exe`
>`P2: 1.0.0.0`
>`P3: 05d857a0`
>`P4: Qt5Qml.dll`
>`P5: 5.4.0.0`
>`P6: 073a7bc0`
>`P7: c000041d`
>`P8: 00127380`

And this error Messages is logged:
>`Faulting application name: cutegram.exe, version: 1.0.0.0, time stamp: 0x05d857a0`
>`Faulting module name: Qt5Qml.dll, version: 5.4.0.0, time stamp: 0x073a7bc0`
>`Exception code: 0xc0000005`
>`Fault offset: 0x00127380`
>`Faulting process ID: 0x1fe0`
>`Faulting application start time: 0x01d0a4f03cd97eb7`
>`Faulting application path: D:\Tools\Cutegram\cutegram-2.4.0\cutegram\cutegram.exe`
>`Faulting module path: D:\Tools\Cutegram\cutegram-2.4.0\cutegram\Qt5Qml.dll`
>`Report ID: 9e238c0b-10e3-11e5-82dd-901b0e3f4d89`
>`Faulting package full name: `
>`Faulting package-relative application ID: `

Am I doing something wrong, or is this feature not supported on Windows maschines?
If you are needing further information like a Windbg dump or something else, I'm happy to provide it.

Cheers Simulacron

**Comment by Sollex-21412** [comment]
+1
Crashed in asemandesktoptools.cpp:311
![assert](https://cloud.githubusercontent.com/assets/8397079/8129606/49f6f3dc-1124-11e5-9df9-d905d9906556.png)

**Comment by realbardia** [comment]
Fixed. Thank you for reporting.
