### ISSUE TITLE
[Feature Request] Custom window decoration

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#81]
It would be nice, to have custom window decoration: borders, title, system buttons etc,  (at least on windows), like in tdesktop's telegram.

**Comment by Simulacrux** [comment]
Maybe a export/import function for this window decoration would also be nice. So everyone could share "own" expirences like minimalistic or other styles.

**Comment by realbardia** [comment]
Hi... thank you for suggestion.
This feature is added on the OSX yosemite and el-capitan. We're waiting for the feedback, after It We'll add this feature to the other operating systems :)
