### ISSUE TITLE
[Bug] Notification shows on outgoing message 

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#83]
Steps are:
1. Two different clients (Cutegram and TD)
2. Send something from TD

Obtained result: Popup notification show as incoming message.
Expected result: Don't show any notification on outgoing message.

![notification](https://cloud.githubusercontent.com/assets/8397079/8143248/a400acc2-11bc-11e5-8d1d-52ccddaef3cb.png)

**Comment by realbardia** [comment]
Thank You for reporting. Fixed and Will release soon :)
