### ISSUE TITLE
[Bug] message overlapped when reply is used 

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#85]
![2015-06-13-235639_757x193_scrot](https://cloud.githubusercontent.com/assets/861563/8144773/0a0d1c60-1228-11e5-8cff-d09327eb65ba.png)

If the last message is reply somebody, it may overlay with previous message.

Tested with:
Cutegram 2.4.0 ( built from github )
Archlinux

**Comment by realbardia** [comment]
Thank You for reporting. Fixed and Will release soon :)
