### ISSUE TITLE
Some dialogs are untranslatable

### ISSUE THREAD

**Issue by softastur** [Aseman-Land/Cutegram#9]
As i said in the title, "Proxy settings", "About (Cutegram/Aseman)", "Custom" and "System color" words are untranslatable in settings menu, also the second line of Aseman description is not translated correctly. However there are others strings like "Hijri", "2Shanbe", "Moharram" etc which i have no idea where they are and what mean.

I attach screenshoots:

![screenshot from 2015-02-12 01 25 03](https://cloud.githubusercontent.com/assets/10351697/6159479/5d1dce22-b256-11e4-9e40-45fcb90abcdd.png)

![screenshot from 2015-02-12 01 26 42](https://cloud.githubusercontent.com/assets/10351697/6159487/76c71c0c-b256-11e4-825b-9b9269bcef50.png)

![screenshot from 2015-02-12 01 51 32](https://cloud.githubusercontent.com/assets/10351697/6159711/c3e81d76-b259-11e4-8518-4cdd8bb178c8.png)

Thank you.

**Comment by realbardia** [comment]
They are AsemanQtTools words. It's a set of tools we are using on our projects and "Hijri", "2shanbe" and ... are words of other calendars.
It's not necessary to translate them, because we are not using calendar features in cutegram.
Maybe I remove them from translation files.

Translation files updates. 
Thank you for reporting :)

**Comment by softastur** [comment]
I compiled again to verify the fix but the problem was not solved yet.

**Comment by realbardia** [comment]
I test it again and it works!
I also update translation binaries. Proxy settings in Asturian translation not translated. But about page works fine now.

**Comment by softastur** [comment]
I discovered another untraslatable string "Just drag and drop contacts here".

**Comment by realbardia** [comment]
Thank you. Fixed :)
