### ISSUE TITLE
[Feature Request] Option to ignore muted message count on systray icon

### ISSUE THREAD

**Issue by farseerfc** [Aseman-Land/Cutegram#90]
Some groups are muted because the user don't want to be notified by the new messages, while other groups are left unmuted because the user want to be notified. Current message count on systray icon can not tell the new messages in **unmuted** groups from **muted** groups. Therefore I think there should be an option to show only message count from **unmuted** groups.
BTW the message count of the android app behaves like this.

**Comment by realbardia** [comment]
There is an option on chats and contacts settings page (show badge) you can uncheck to exclude from unread count.
