### ISSUE TITLE
[Bug] To many data is written

### ISSUE THREAD

**Issue by MaximKraev** [Aseman-Land/Cutegram#94]
The program writes about 100Mb of data in 2 minutes, there no synchronization, or any other activity, also write can be triggered with focus switch.
version: 2.4.0
http://i.imgur.com/w3kjFOc.png

**Comment by legion1978** [comment]
hi. what is this command (to see the disk write activity)? thank you :)

**Comment by MaximKraev** [comment]
iotop -Pa

**Comment by legion1978** [comment]
cool thnx :)

**Comment by realbardia** [comment]
Fixed... Thank you for reporting :)
