### ISSUE TITLE
[Bug] Forward message doesn't work

### ISSUE THREAD

**Issue by Sollex-21412** [Aseman-Land/Cutegram#99]
Console output:
<pre>
qrc:/qml/Cutegram/ForwardPage.qml:70: TypeError: Cannot read property 'message' of null
qrc:/qml/Cutegram/ForwardPage.qml:34: TypeError: Cannot read property 'fromId' of null
TelegramQml::error "MESSAGE_ID_EMPTY" "Api::messagesForwardMessage"
</pre>

**Comment by Sollex-21412** [comment]
Cannot replicate this issue with latest source from git.

**Comment by realbardia** [comment]
Yes. It's fixed for me too. I think it was because a bug on memory clean system.
